stages:
  - build

build:1.20:
  stage: build
  image: golang:1.20
  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
    - go build xxwcli.go
  artifacts:
    paths:
      - xxwcli
  only:
    - main
