stages:
  - build

build:1.20:
  stage: build
  image: golang:1.20
  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
    - go build xxwcli.go
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - xxwcli
  only:
    - main

build:1.20-windowsservercore-ltsc2022:
  stage: build
  image: golang:1.20-windowsservercore-ltsc2022
  script:
    - go env -w GOPROXY=https://goproxy.cn,direct
    - go mod download
    - go build xxwcli.go
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - xxwcli.exe
  tags:
    - windows
  only:
    - main
