# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    strategy:
      matrix:
        os: [ "ubuntu-latest", "windows-latest", "macos-latest" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod/cache
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build
        run: |
          go version
          go mod download
          go build xxwcli.go
          ls

#      - name: Set OS variable
#        id: os
#        run: |
#          echo "os=matrix.os" >> $GITHUB_STATE

      - name: Get current date
        id: date
        run: |
          echo "year_month_day=$(date +'%Y%m%d')" >> $GITHUB_STATE
          echo "year_month_day_hour=$(date +'%Y%m%d%H')" >> $GITHUB_STATE
          echo "year_month_day_hour_minute=$(date +'%Y%m%d%H%M')" >> $GITHUB_STATE

      - uses: actions/upload-artifact@v3
        with:
          name: xxwcli-${{ matrix.os }}-${{ steps.date.outputs.year_month_day_hour_minute }}
          path: |
            xxwcli
            xxwcli.exe

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            xxwcli
            xxwcli.exe
          prerelease: true
          name: ${{ matrix.os }}-${{ steps.date.outputs.year_month_day_hour_minute }}
          tag: v-${{ matrix.os }}-${{ steps.date.outputs.year_month_day_hour_minute }}
          token: ${{ secrets.GITHUB_TOKEN }}
